// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
	"kratos-blog/app/user/service/internal/biz"
	"kratos-blog/app/user/service/internal/conf"
	"kratos-blog/app/user/service/internal/data"
	"kratos-blog/app/user/service/internal/server"
	"kratos-blog/app/user/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	cardRepo := data.NewCardRepo(dataData, logger)
	cardUseCase := biz.NewCardUseCase(cardRepo, logger)
	addressRepo := data.NewAddressRepo(dataData, logger)
	addressUseCase := biz.NewAddressUseCase(addressRepo, logger)
	userService := service.NewUserService(userUseCase, cardUseCase, addressUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, tracerProvider, userService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
