// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
	"kratos-blog/app/moment/interface/internal/biz"
	"kratos-blog/app/moment/interface/internal/conf"
	"kratos-blog/app/moment/interface/internal/data"
	"kratos-blog/app/moment/interface/internal/server"
	"kratos-blog/app/moment/interface/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(discovery, tracerProvider)
	dataData, cleanup, err := data.NewData(confData, logger, userClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	momentInterface := service.NewMomentInterface(userUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, tracerProvider, momentInterface)
	grpcServer := server.NewGRPCServer(confServer, logger, tracerProvider, momentInterface)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
