// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/shipping/service/v1/shipping.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ShipOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShipOrderReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShipOrderReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShipOrderReqMultiError, or
// nil if none found.
func (m *ShipOrderReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ShipOrderReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ShipOrderReqMultiError(errors)
	}
	return nil
}

// ShipOrderReqMultiError is an error wrapping multiple validation errors
// returned by ShipOrderReq.ValidateAll() if the designated constraints aren't met.
type ShipOrderReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShipOrderReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShipOrderReqMultiError) AllErrors() []error { return m }

// ShipOrderReqValidationError is the validation error returned by
// ShipOrderReq.Validate if the designated constraints aren't met.
type ShipOrderReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShipOrderReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShipOrderReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShipOrderReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShipOrderReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShipOrderReqValidationError) ErrorName() string { return "ShipOrderReqValidationError" }

// Error satisfies the builtin error interface
func (e ShipOrderReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShipOrderReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShipOrderReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShipOrderReqValidationError{}

// Validate checks the field values on ShipOrderReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShipOrderReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShipOrderReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShipOrderReplyMultiError,
// or nil if none found.
func (m *ShipOrderReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ShipOrderReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ShipOrderReplyMultiError(errors)
	}
	return nil
}

// ShipOrderReplyMultiError is an error wrapping multiple validation errors
// returned by ShipOrderReply.ValidateAll() if the designated constraints
// aren't met.
type ShipOrderReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShipOrderReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShipOrderReplyMultiError) AllErrors() []error { return m }

// ShipOrderReplyValidationError is the validation error returned by
// ShipOrderReply.Validate if the designated constraints aren't met.
type ShipOrderReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShipOrderReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShipOrderReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShipOrderReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShipOrderReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShipOrderReplyValidationError) ErrorName() string { return "ShipOrderReplyValidationError" }

// Error satisfies the builtin error interface
func (e ShipOrderReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShipOrderReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShipOrderReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShipOrderReplyValidationError{}
