// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/payment/service/v1/payment.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on PaymentAuthReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaymentAuthReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentAuthReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaymentAuthReqMultiError,
// or nil if none found.
func (m *PaymentAuthReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentAuthReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PaymentAuthReqMultiError(errors)
	}
	return nil
}

// PaymentAuthReqMultiError is an error wrapping multiple validation errors
// returned by PaymentAuthReq.ValidateAll() if the designated constraints
// aren't met.
type PaymentAuthReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentAuthReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentAuthReqMultiError) AllErrors() []error { return m }

// PaymentAuthReqValidationError is the validation error returned by
// PaymentAuthReq.Validate if the designated constraints aren't met.
type PaymentAuthReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentAuthReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentAuthReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentAuthReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentAuthReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentAuthReqValidationError) ErrorName() string { return "PaymentAuthReqValidationError" }

// Error satisfies the builtin error interface
func (e PaymentAuthReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentAuthReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentAuthReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentAuthReqValidationError{}

// Validate checks the field values on PaymentAuthReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PaymentAuthReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentAuthReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentAuthReplyMultiError, or nil if none found.
func (m *PaymentAuthReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentAuthReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PaymentAuthReplyMultiError(errors)
	}
	return nil
}

// PaymentAuthReplyMultiError is an error wrapping multiple validation errors
// returned by PaymentAuthReply.ValidateAll() if the designated constraints
// aren't met.
type PaymentAuthReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentAuthReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentAuthReplyMultiError) AllErrors() []error { return m }

// PaymentAuthReplyValidationError is the validation error returned by
// PaymentAuthReply.Validate if the designated constraints aren't met.
type PaymentAuthReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentAuthReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentAuthReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentAuthReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentAuthReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentAuthReplyValidationError) ErrorName() string { return "PaymentAuthReplyValidationError" }

// Error satisfies the builtin error interface
func (e PaymentAuthReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentAuthReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentAuthReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentAuthReplyValidationError{}
