// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
	"kratos-blog/app/moment/admin/internal/biz"
	"kratos-blog/app/moment/admin/internal/conf"
	"kratos-blog/app/moment/admin/internal/data"
	"kratos-blog/app/moment/admin/internal/server"
	"kratos-blog/app/moment/admin/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	discovery := biz.NewDiscovery()
	userClient := biz.NewUserServiceClient(discovery)
	userUseCase := biz.NewUserUseCase(userRepo, logger, userClient)
	shopAdmin := service.NewShopAdmin(userUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, tracerProvider, shopAdmin)
	grpcServer := server.NewGRPCServer(confServer, logger, tracerProvider, shopAdmin)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
